name: Playwright Tests on Dev

on:
  workflow_dispatch:

jobs:
  test-release:
    name: Run tests on Release environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.27"
          enable-cache: true
          cache-dependency-glob: "requirements**.txt"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt

      - name: Ensure browsers are installed
        run: |
          uv pip install --system playwright
          python -m playwright install --with-deps

      - name: Set environment for Release
        run: |
          echo "BASE_URL=https://dev.qa-playground.com/api/v1/" >> $GITHUB_ENV

      - name: Set API Token for Release
        run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

      - name: Create result directories for Release
        run: |
          mkdir -p test-results/release
          mkdir -p allure-results/release

      - name: Run tests for Release
        run: |
          pytest --alluredir=allure-results/release || true
        continue-on-error: true  # Ensures job continues even if tests fail

      - name: Upload Allure results for Release
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-release
          path: allure-results/release
          retention-days: 20
